use_frameworks!

target 'SHLogger_Example' do
  pod 'SHLogger', :path => '../'

  target 'SHLogger_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
